
services:

  mysql:
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    env_file:
      - ./Backend/.env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_HOST=${MYSQL_HOST}
    #   - MYSQL_DATABASE=${MYSQL_DATABASE:-quiz_ai}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - quiz_ai_network 

  backend: 
    build: ./Backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_HOST=${MYSQL_HOST}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - quiz_ai_network
  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - quiz_ai_network
volumes:
  mysql_data:

networks:
  quiz_ai_network:
    driver: bridge