version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    env_file:
      - ./Backend/.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - quiz_ai_network_test

  backend_test:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - mysql
    networks:
      - quiz_ai_network_test
    env_file:
      - ./Backend/.env
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  frontend_test:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend_test
    networks:
      - quiz_ai_network_test

networks:
  quiz_ai_network_test:
    driver: bridge

volumes:
  mysql_data:
