version: '3.8'

services:
  backend_test:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - quiz_ai_network_test
    env_file:
      - ./Backend/.env
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  frontend_test:
    build: ./Frontend
    ports:
      - "3000:80"
    networks:
      - quiz_ai_network_test

networks:
  quiz_ai_network_test:
    driver: bridge

volumes:
  mysql_data:
