apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret       
  namespace: doppler-operator-system
type: Opaque
stringData:
  serviceToken: dp.st.dev.mjkTzz71KLroh6nEtaHZMobAVOYmCxVO4hdYr6fl7wy
